---
title: "Coronavirus Second Wave"
author: "Tyler DeGroff"
date: "6/26/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
rm(list = ls())
library(tidyverse)
library(readxl)
library(httr)
```

```{r}
data <- read.csv(
  'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'
)

data <- data %>% 
  filter(county != "Unknown") %>%
  mutate(date = as.Date(date))

data <- within(data, fips[county == "New York City"] <- 36999) # treats NYC as a county
```

```{r}
GET(
  "https://www2.census.gov/programs-surveys/popest/geographies/2019/state-geocodes-v2019.xlsx",
  write_disk(temp <- tempfile())
)

fips.state <- read_excel(temp, skip = 4) %>%
  rename(fips.state = "State (FIPS)", state = "Name") %>%
  select(fips.state, state) %>%
  filter(fips.state != "00") %>%
  arrange(fips.state)
```

```{r}
GET(
  "https://www2.census.gov/programs-surveys/popest/geographies/2019/all-geocodes-v2019.xlsx",
  write_disk(temp <- tempfile())
)

fips.county <- read_excel(temp, skip = 4) %>%
  rename(
    fips.state = "State Code (FIPS)", 
    fips.county = "County Code (FIPS)",
    county = "Area Name (including legal/statistical area description)"
  ) %>%
  mutate(
    fips = as.numeric(paste0(as.character(fips.state), as.character(fips.county)))
  ) %>%
  select(fips, fips.state, fips.county, county) %>%
  filter(fips.county != "000") %>%
  arrange(fips)
```

```{r}
fips <- merge(
  x = fips.county,
  y = fips.state,
  by = "fips.state",
  all.x = TRUE
)

fips <- fips[complete.cases(fips[, "state"]), ]
```

```{r}
GET(
  "https://www2.census.gov/programs-surveys/popest/tables/2010-2019/counties/totals/co-est2019-annres.xlsx",
  write_disk(temp <- tempfile())
)

pop <- read_excel(temp, skip = 3) %>%
  rename(countyState = "...1", population = "2019") %>%
  select(countyState, population) %>%
  filter(countyState != "United States") %>%
  mutate(
    countyState = ifelse(
      countyState == "Bottineau County, North Dakota", 
      ".Bottineau County, North Dakota", # accounts for a one-time data issue at source
      countyState
    ), 
    countyState = sub(".", "", countyState))

fips <- fips %>% mutate(countyState = paste0(county, ", ", state))

pop <- merge(
  x = pop,
  y = fips,
  by = "countyState",
  all.x = TRUE
)
```

```{r}
pop.nyc <- pop %>%
  filter(
    fips == 36005 | # Bronx County or Bronx
    fips == 36047 | # Kings County or Brooklyn
    fips == 36061 | # New York County or Manhattan
    fips == 36081 | # Queens County or Queens
    fips == 36085   # Richmond County or Staten Island
  )

pop <- rbind(
  pop,
  data.frame(
    fips.state = "36", # actual New York State state-level FIPS code
    fips.county = "999", # synthetic county-level FIPS code
    fips = "36999", # synthetic FIPS code
    county = "New York City",
    state = "New York",
    countyState = "New York, New York",
    population = sum(pop.nyc$population)
  )
)
```

```{r}
data <- merge(
  x = data, 
  y = pop %>% select(fips, population),
  by = "fips",
  all.x = TRUE
)

# county-level cases and deaths per capita or per 100K data only valid for New York State
# county-level population data was not imported for any other state. NAs result.

data <- data %>% 
  mutate(
    cases.percap = cases / population,
    cases.per100k = cases / (population / 100000),
    deaths.percap = deaths / population,
    deaths.per100k = deaths / (population / 100000)
  )
```

```{r, results = "hide"}
data <- data[order(data$date, data$state, data$county), ]
states <- sort(unique(data$state))
temp <- data.frame()

for (i in 1:length(states)) {
  
  counties <- sort(unique(data %>% filter(state == states[i]) %>% select(county))[, 1])
  
  for (j in 1:length(counties)) {
    
    temp2 <- data %>% 
      filter(
        state == states[i],
        county == counties[j]
      ) %>%
      mutate(
        cases.new = c(cases[1], diff(cases)),
        deaths.new = c(deaths[1], diff(deaths))
      )
    
    temp <- rbind(temp, temp2)
    
    print(paste(states[i], "->", counties[j]))
    
  }
  
}

data <- temp

rm(list = c("i", "j", ls(pattern = "temp")))
```

```{r}
write_csv(data, "data.csv")
```